services:
  # frontend:
  #   build: ./frontend
  #   ports:
  #     - 3000:3000
  #   working_dir: /app-frontend
  #   volumes: 
  #     - ./frontend/src:/app-frontend/src
  #   depends_on:
  #     - backend
  backend:
    container_name: app_backend
    build: ./backend
    ports:
      - 8000:8000
    working_dir: /app-backend
    environment:
        DATABASE_URL: "postgres://postgres:123456@db:5432/matricula-db"
    command: npm run dev
    volumes: 
      - ./backend/src:/app-backend/src
    depends_on:
      - db
  db:
    image: postgres
    container_name: db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456